In [1]:
import pandas as pd
import numpy as np
from ast import literal_eval
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load data
# converters to evaluate 'details_list' column as a list instead of strings
#df = pd.read_csv('unegui_test.csv', converters={'details_list': literal_eval})
df = pd.read_csv('unegui_full_adj.csv', converters={'details_list': literal_eval})
df.head()

,posting_name,posting_link,price,date_posted,details_list,description
0,–ù–æ–º–∏–Ω –∫–æ–Ω—Å—Ç—Ä–∞–∫—à–Ω—ã —è–∞—Ä–º–∞–≥—Ç garden city 2 —Ç”©—Å”©–ª–¥...,https://www.unegui.mn/adv/5307817_nomin-konstr...,360000000.0,"”®–Ω”©”©–¥”©—Ä 11:16, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä","[–ü–∞—Ä–∫–µ—Ç, 2 —Ç–∞–≥—Ç—Ç–∞–π, 2021, –ë–∞–π—Ö–≥“Ø–π, –¢”©–º”©—Ä –≤–∞–∫—É–º...",‚Äú–ù–û–ú–ò–ù –ö–û–ù–°–¢–†–ê–ö–®–ù‚Äù-—ã –ë“Æ–¢–≠–≠–ù –ë–ê–ô–ì–£–£–õ–ê–õ–¢ GARDENC...
1,"Harhorin horoolold 58,2mkv 2oroo bair",https://www.unegui.mn/adv/5844945_harhorin-hor...,155000000.0,"”®–Ω”©”©–¥”©—Ä 11:16, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä","[–ü–∞—Ä–∫–µ—Ç, 1 —Ç–∞–≥—Ç—Ç–∞–π, 2019, –ë–∞–π—Ö–≥“Ø–π, –í–∞–∫—É–º, 16, ...","Harhorin horoolold 58,19mkv 2oroo bair hudalda..."
2,–•–∞–Ω–≥–∞–π —Ö–æ—Ç—Ö–æ–Ω–¥ 2”©—Ä”©”© –±–∞–π—Ä 37.08–º2,https://www.unegui.mn/adv/5843673_khangai-khot...,98000000.0,"”®–Ω”©”©–¥”©—Ä 11:16, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä","[–ü–∞—Ä–∫–µ—Ç, 1 —Ç–∞–≥—Ç—Ç–∞–π, 2018, –ë–∞–π—Ö–≥“Ø–π, –í–∞–∫—É–º, 12, ...",–•–∞–Ω–≥–∞–π —Ö–æ—Ç—Ö–æ–Ω–¥ 2”©—Ä”©”© 37.08–º–∫–≤ -12/11–¥–∞–≤—Ö–∞—Ä—Ç-–ì—ç...
3,–¢”©–º”©—Ä –∑–∞–º–¥ 3 ”©—Ä”©”©,https://www.unegui.mn/adv/5632308_tomor-zamd-3...,150000000.0,"”®–Ω”©”©–¥”©—Ä 11:12, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä","[–ü–∞—Ä–∫–µ—Ç, 1 —Ç–∞–≥—Ç—Ç–∞–π, 1980, –ë–∞–π—Ö–≥“Ø–π, –í–∞–∫—É–º, 5, –ë...","üè°–ë–∞—è–Ω–≥–æ–ª –¥“Ø“Ø—Ä—ç–≥, –¢”©–º”©—Ä –∑–∞–º, –ë–æ–≥–¥ –∞—Ä —Ö–æ—Ä–æ–æ–ª–æ–ª—ã–Ω..."
4,–ê–ª—Ç–∞–Ω –±–æ–≥–¥ —Ü–æ–≥—Ü–æ–ª–±–æ—Ä—Ç 4 ”©—Ä”©”© –±–∞–π—Ä,https://www.unegui.mn/adv/5494189_altan-bogd-t...,3100000.0,"”®–Ω”©”©–¥”©—Ä 11:12, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä","[–ü–∞—Ä–∫–µ—Ç, 1 —Ç–∞–≥—Ç—Ç–∞–π, 2021, –ë–∞–π—Ö–≥“Ø–π, –í–∞–∫—É–º, 12, ...",–ó–∞–π—Å–∞–Ω–¥ –±–∞–π—Ä–ª–∞–ª—Ç–∞–π –æ–¥–æ–æ –∞—à–∏–≥–ª–∞–ª—Ç–∞–Ω–¥ –æ—Ä–∂ –±–∞–π–≥–∞–∞...

In [3]:
# expand list to columns
df1 = pd.DataFrame(df.details_list.to_list(), 
                   columns=['flr_type','balcony', 'yr_built', 'garage', 'window_type',
                            'building_height', 'door_type', 'area', 'flr_lvl', 'mortgage',
                            'district', 'window_n', 'location', 'col1'])

In [4]:
# row index numbers for misplaced values in col1
idx = df1.query('col1==col1').index.values
df1.query('col1==col1')

,flr_type,balcony,yr_built,garage,window_type,building_height,door_type,area,flr_lvl,mortgage,district,window_n,location,col1
49,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2009,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,9,–ë“Ø—Ä–≥—ç–¥,30.0 –º¬≤,1,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–ë–∞—è–Ω–≥–æ–ª,1 davhar 2 oroo huuchnii 30 mk2,3,6-—Ä –±–∏—á–∏–ª
128,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2003,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,6,–¢”©–º”©—Ä,68.0 –º¬≤,2,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–ë–∞—è–Ω–≥–æ–ª,25-—Ä —ç–º–∏–π–Ω —Å–∞–Ω,3,25-—Ä —ç–º–∏–π–Ω —Å–∞–Ω
172,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2011,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,15,–ë“Ø—Ä–≥—ç–¥,37.63 –º¬≤,11,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–ë–∞—è–Ω–∑“Ø—Ä—Ö,–ñ–æ–±–∏ 72 –∏–π–Ω –∑–∞–º—ã–Ω —á–∞–Ω—Ö —É—Ä–¥,2,13-—Ä —Ö–æ—Ä–æ–æ–ª–æ–ª
188,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2022,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,15,–ú–æ–¥,59.0 –º¬≤,3,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–•–∞–Ω-–£—É–ª,–ê–ª—Ç–∞–π —Ö–æ—Ç—Ö–æ–Ω—ã –∑–∞–º—ã–Ω —ç—Å—Ä—ç–≥ —Ç–∞–ª–¥,3,–ë—É—Å–∞–¥
212,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2021,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,16,–¢”©–º”©—Ä,74.68 –º¬≤,16,–ë–∞–Ω–∫–Ω—ã –ª–∏–∑–∏–Ω–≥—Ç—ç–π,–•–∞–Ω-–£—É–ª,—Ö“Ø–Ω–Ω“Ø –º–æ–ª–ª—ã–Ω –∑–∞–º—ã–Ω —É—Ä–¥,4,–Ø–∞—Ä–º–∞–≥
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2014,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,14,–ë“Ø—Ä–≥—ç–¥,65.0 –º¬≤,6,–ë–∞–Ω–∫–Ω—ã –ª–∏–∑–∏–Ω–≥—Ç—ç–π,–ë–∞—è–Ω–∑“Ø—Ä—Ö,–Ω–∞—Ç—É—Ä—Ç,2,–ë—É—Å–∞–¥
7073,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2022,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,16,–¢”©–º”©—Ä,79.06 –º¬≤,8,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–•–∞–Ω-–£—É–ª,–®–∏–Ω—ç —Ö–æ—Ç—ã–Ω –∑–∞—Ö–∏—Ä–≥–∞–∞,3,–Ø–∞—Ä–º–∞–≥
7077,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2020,–ë–∞–π–≥–∞–∞,–í–∞–∫—É–º,12,–ë“Ø—Ä–≥—ç–¥,67.0 –º¬≤,6,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–ë–∞—è–Ω–≥–æ–ª,Ulaanbaatar,5,"3, 4 —Ö–æ—Ä–æ–æ–ª–æ–ª"
7081,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,1998,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,9,–ë“Ø—Ä–≥—ç–¥,30.0 –º¬≤,9,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–ë–∞—è–Ω–≥–æ–ª,28-—Ä —Å—É—Ä–≥—É—É–ª–∏–π–Ω —Ö–∞–∂—É—É —Ç–∞–ª–¥,4,6-—Ä –±–∏—á–∏–ª
7103,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2004,–ë–∞–π–≥–∞–∞,–í–∞–∫—É–º,12,–ë“Ø—Ä–≥—ç–¥,80.0 –º¬≤,5,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–°“Ø—Ö–±–∞–∞—Ç–∞—Ä,2-—Ä —Ö–æ—Ä–æ–æ,5,–ë—É—Å–∞–¥

In [5]:
# replace values into correct column
df1.iloc[idx, 11] = df1.iloc[idx, 12]
df1.iloc[idx, 12] = df1.iloc[idx, 13]

In [6]:
df1.iloc[idx,]

,flr_type,balcony,yr_built,garage,window_type,building_height,door_type,area,flr_lvl,mortgage,district,window_n,location,col1
49,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2009,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,9,–ë“Ø—Ä–≥—ç–¥,30.0 –º¬≤,1,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–ë–∞—è–Ω–≥–æ–ª,3,6-—Ä –±–∏—á–∏–ª,6-—Ä –±–∏—á–∏–ª
128,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2003,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,6,–¢”©–º”©—Ä,68.0 –º¬≤,2,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–ë–∞—è–Ω–≥–æ–ª,3,25-—Ä —ç–º–∏–π–Ω —Å–∞–Ω,25-—Ä —ç–º–∏–π–Ω —Å–∞–Ω
172,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2011,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,15,–ë“Ø—Ä–≥—ç–¥,37.63 –º¬≤,11,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–ë–∞—è–Ω–∑“Ø—Ä—Ö,2,13-—Ä —Ö–æ—Ä–æ–æ–ª–æ–ª,13-—Ä —Ö–æ—Ä–æ–æ–ª–æ–ª
188,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2022,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,15,–ú–æ–¥,59.0 –º¬≤,3,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–•–∞–Ω-–£—É–ª,3,–ë—É—Å–∞–¥,–ë—É—Å–∞–¥
212,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2021,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,16,–¢”©–º”©—Ä,74.68 –º¬≤,16,–ë–∞–Ω–∫–Ω—ã –ª–∏–∑–∏–Ω–≥—Ç—ç–π,–•–∞–Ω-–£—É–ª,4,–Ø–∞—Ä–º–∞–≥,–Ø–∞—Ä–º–∞–≥
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2014,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,14,–ë“Ø—Ä–≥—ç–¥,65.0 –º¬≤,6,–ë–∞–Ω–∫–Ω—ã –ª–∏–∑–∏–Ω–≥—Ç—ç–π,–ë–∞—è–Ω–∑“Ø—Ä—Ö,2,–ë—É—Å–∞–¥,–ë—É—Å–∞–¥
7073,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2022,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,16,–¢”©–º”©—Ä,79.06 –º¬≤,8,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–•–∞–Ω-–£—É–ª,3,–Ø–∞—Ä–º–∞–≥,–Ø–∞—Ä–º–∞–≥
7077,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2020,–ë–∞–π–≥–∞–∞,–í–∞–∫—É–º,12,–ë“Ø—Ä–≥—ç–¥,67.0 –º¬≤,6,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–ë–∞—è–Ω–≥–æ–ª,5,"3, 4 —Ö–æ—Ä–æ–æ–ª–æ–ª","3, 4 —Ö–æ—Ä–æ–æ–ª–æ–ª"
7081,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,1998,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,9,–ë“Ø—Ä–≥—ç–¥,30.0 –º¬≤,9,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–ë–∞—è–Ω–≥–æ–ª,4,6-—Ä –±–∏—á–∏–ª,6-—Ä –±–∏—á–∏–ª
7103,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2004,–ë–∞–π–≥–∞–∞,–í–∞–∫—É–º,12,–ë“Ø—Ä–≥—ç–¥,80.0 –º¬≤,5,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–°“Ø—Ö–±–∞–∞—Ç–∞—Ä,5,–ë—É—Å–∞–¥,–ë—É—Å–∞–¥

In [7]:
df2 = df1.drop('col1', 1)

In [8]:
# df checkpoint
df3 = (pd.concat([df2, df], 1)
       .drop(['details_list'],1)
       .drop_duplicates()
       .query("district == ['–•–∞–Ω-–£—É–ª', '–°–æ–Ω–≥–∏–Ω–æ –•–∞–π—Ä—Ö–∞–Ω', '–°“Ø—Ö–±–∞–∞—Ç–∞—Ä', '–ë–∞—è–Ω–≥–æ–ª', '–ë–∞—è–Ω–∑“Ø—Ä—Ö','–ß–∏–Ω–≥—ç–ª—Ç—ç–π']")
       .reset_index(drop=True)
      )
df3.head()

,flr_type,balcony,yr_built,garage,window_type,building_height,door_type,area,flr_lvl,mortgage,district,window_n,location,posting_name,posting_link,price,date_posted,description
0,–ü–∞—Ä–∫–µ—Ç,2 —Ç–∞–≥—Ç—Ç–∞–π,2021,–ë–∞–π—Ö–≥“Ø–π,–¢”©–º”©—Ä –≤–∞–∫—É–º,17,–ë“Ø—Ä–≥—ç–¥,79.2 –º¬≤,15,–ë–∞–Ω–∫–Ω—ã –ª–∏–∑–∏–Ω–≥—Ç—ç–π,–•–∞–Ω-–£—É–ª,4,–Ø–∞—Ä–º–∞–≥,–ù–æ–º–∏–Ω –∫–æ–Ω—Å—Ç—Ä–∞–∫—à–Ω—ã —è–∞—Ä–º–∞–≥—Ç garden city 2 —Ç”©—Å”©–ª–¥...,https://www.unegui.mn/adv/5307817_nomin-konstr...,360000000.0,"”®–Ω”©”©–¥”©—Ä 11:16, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä",‚Äú–ù–û–ú–ò–ù –ö–û–ù–°–¢–†–ê–ö–®–ù‚Äù-—ã –ë“Æ–¢–≠–≠–ù –ë–ê–ô–ì–£–£–õ–ê–õ–¢ GARDENC...
1,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2019,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,16,–ë“Ø—Ä–≥—ç–¥,59.0 –º¬≤,2,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–°–æ–Ω–≥–∏–Ω–æ –•–∞–π—Ä—Ö–∞–Ω,2,1-—Ä —Ö–æ—Ä–æ–æ–ª–æ–ª,"Harhorin horoolold 58,2mkv 2oroo bair",https://www.unegui.mn/adv/5844945_harhorin-hor...,155000000.0,"”®–Ω”©”©–¥”©—Ä 11:16, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä","Harhorin horoolold 58,19mkv 2oroo bair hudalda..."
2,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2018,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,12,–ë“Ø—Ä–≥—ç–¥,37.08 –º¬≤,11,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–°“Ø—Ö–±–∞–∞—Ç–∞—Ä,2,11-—Ä —Ö–æ—Ä–æ–æ–ª–æ–ª,–•–∞–Ω–≥–∞–π —Ö–æ—Ç—Ö–æ–Ω–¥ 2”©—Ä”©”© –±–∞–π—Ä 37.08–º2,https://www.unegui.mn/adv/5843673_khangai-khot...,98000000.0,"”®–Ω”©”©–¥”©—Ä 11:16, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä",–•–∞–Ω–≥–∞–π —Ö–æ—Ç—Ö–æ–Ω–¥ 2”©—Ä”©”© 37.08–º–∫–≤ -12/11–¥–∞–≤—Ö–∞—Ä—Ç-–ì—ç...
3,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,1980,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,5,–ë“Ø—Ä–≥—ç–¥,69.0 –º¬≤,3,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–ë–∞—è–Ω–≥–æ–ª,4,–¢”©–º”©—Ä –∑–∞–º,–¢”©–º”©—Ä –∑–∞–º–¥ 3 ”©—Ä”©”©,https://www.unegui.mn/adv/5632308_tomor-zamd-3...,150000000.0,"”®–Ω”©”©–¥”©—Ä 11:12, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä","üè°–ë–∞—è–Ω–≥–æ–ª –¥“Ø“Ø—Ä—ç–≥, –¢”©–º”©—Ä –∑–∞–º, –ë–æ–≥–¥ –∞—Ä —Ö–æ—Ä–æ–æ–ª–æ–ª—ã–Ω..."
4,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2021,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,12,–ë“Ø—Ä–≥—ç–¥,90.39 –º¬≤,4,–•—É–≤—å –ª–∏–∑–∏–Ω–≥—Ç—ç–π,–•–∞–Ω-–£—É–ª,4,–ó–∞–π—Å–∞–Ω,–ê–ª—Ç–∞–Ω –±–æ–≥–¥ —Ü–æ–≥—Ü–æ–ª–±–æ—Ä—Ç 4 ”©—Ä”©”© –±–∞–π—Ä,https://www.unegui.mn/adv/5494189_altan-bogd-t...,3100000.0,"”®–Ω”©”©–¥”©—Ä 11:12, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä",–ó–∞–π—Å–∞–Ω–¥ –±–∞–π—Ä–ª–∞–ª—Ç–∞–π –æ–¥–æ–æ –∞—à–∏–≥–ª–∞–ª—Ç–∞–Ω–¥ –æ—Ä–∂ –±–∞–π–≥–∞–∞...

In [9]:
df3.info()
df3.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6952 entries, 0 to 6951
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   flr_type         6952 non-null   object
 1   balcony          6952 non-null   object
 2   yr_built         6952 non-null   object
 3   garage           6952 non-null   object
 4   window_type      6952 non-null   object
 5   building_height  6952 non-null   object
 6   door_type        6952 non-null   object
 7   area             6952 non-null   object
 8   flr_lvl          6952 non-null   object
 9   mortgage         6952 non-null   object
 10  district         6952 non-null   object
 11  window_n         6952 non-null   object
 12  location         6952 non-null   object
 13  posting_name     6952 non-null   object
 14  posting_link     6952 non-null   object
 15  price            6952 non-null   float64
 16  date_posted      6952 non-null   object
 17  description      6952 non-null   object
dtypes: float64(1), object(17)
memory usage: 977.8+ KB

,flr_type,balcony,yr_built,garage,window_type,building_height,door_type,area,flr_lvl,mortgage,district,window_n,location,posting_name,posting_link,price,date_posted,description
count,6952,6952,6952,6952,6952,6952,6952,6952,6952,6952,6952,6952,6952,6952,6952,6.952000e+03,6952,6952
unique,6,4,43,2,4,25,5,1583,25,3,6,8,78,6252,6952,NaN,5384,6824
top,–ü–∞—Ä–∫–µ—Ç,1 —Ç–∞–≥—Ç—Ç–∞–π,2022,–ë–∞–π—Ö–≥“Ø–π,–í–∞–∫—É–º,16,–ë“Ø—Ä–≥—ç–¥,55.0 –º¬≤,5,–õ–∏–∑–∏–Ω–≥–≥“Ø–π,–•–∞–Ω-–£—É–ª,2,–ë—É—Å–∞–¥,2 ”©—Ä”©”© –±–∞–π—Ä,https://www.unegui.mn/adv/5799934_bzd-t-shine-...,NaN,"”®–Ω”©”©–¥”©—Ä 11:12, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä",–∑–∞—Ä–Ω–∞
freq,6668,5376,1690,5426,6557,1701,5379,109,714,5379,3006,1996,1255,107,1,NaN,10,5
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.735049e+08,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.092993e+08,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.788000e+07,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.280000e+08,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.072000e+08,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.700000e+09,NaN,NaN

In [10]:
#df3.location.value_counts()
df3.date_posted.unique()
#df3.query("flr_type == '–ß—É–ª—É—É'").posting_link

array(['”®–Ω”©”©–¥”©—Ä 11:16,            –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä',
       '”®–Ω”©”©–¥”©—Ä 11:12,            –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä',
       '”®–Ω”©”©–¥”©—Ä 11:11,            –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä', ...,
       '2022-02-22 11:29,            –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä',
       '2022-02-22 11:27,            –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä',
       '2022-02-22 11:22,            –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä'], dtype=object)

In [11]:
# Clean data
#df3.flr_type.unique()
df3 = (pd.concat([df2, df], 1)
       .drop(['details_list'],1)
       .drop_duplicates()
       .query("district == ['–•–∞–Ω-–£—É–ª', '–°–æ–Ω–≥–∏–Ω–æ –•–∞–π—Ä—Ö–∞–Ω', '–°“Ø—Ö–±–∞–∞—Ç–∞—Ä', '–ë–∞—è–Ω–≥–æ–ª', '–ë–∞—è–Ω–∑“Ø—Ä—Ö','–ß–∏–Ω–≥—ç–ª—Ç—ç–π']")
       .reset_index(drop=True)
      )
df3.head()
df3 = (df3
       .replace({'flr_type':{'–ü–∞—Ä–∫–µ—Ç': 'parquet', '–ú–æ–¥':'wooden', '–õ–∞–º–∏–Ω–∞—Ç':'laminate', '–¶–µ–º–µ–Ω—Ç': 'tile', '–ß—É–ª—É—É':'tile', '–ü–ª–∏—Ç–∞': 'tile'}
                 , 'garage':{'–ë–∞–π—Ö–≥“Ø–π':0, '–ë–∞–π–≥–∞–∞':1}
                 , 'window_type':{'–í–∞–∫—É–º':'vinyl', '–¢”©–º”©—Ä –≤–∞–∫—É–º':'alum', '–ú–æ–¥':'wooden', '–ú–æ–¥–æ–Ω –≤–∞–∫—É–º':'clad_wood'}
                 , 'door_type':{'–ë“Ø—Ä–≥—ç–¥':'burged', '–¢”©–º”©—Ä –≤–∞–∫—É–º':'alum', '–¢”©–º”©—Ä':'metal', '–í–∞–∫—É–º':'vinyl', '–ú–æ–¥':'wooden'}
                 , 'mortgage':{'–õ–∏–∑–∏–Ω–≥–≥“Ø–π':'no', '–ë–∞–Ω–∫–Ω—ã –ª–∏–∑–∏–Ω–≥—Ç—ç–π':'bank', '–•—É–≤—å –ª–∏–∑–∏–Ω–≥—Ç—ç–π':'personal'}
                 , 'district':{'–•–∞–Ω-–£—É–ª':'KU', '–°–æ–Ω–≥–∏–Ω–æ –•–∞–π—Ä—Ö–∞–Ω':'SH', '–°“Ø—Ö–±–∞–∞—Ç–∞—Ä':'SU', '–ë–∞—è–Ω–≥–æ–ª':'BG', '–ë–∞—è–Ω–∑“Ø—Ä—Ö':'BZ', '–ß–∏–Ω–≥—ç–ª—Ç—ç–π':'CH'}
                })
       .assign(balcony = lambda x: x.balcony.str.extract('(\d+)')
               , area = lambda x: x.area.str.split(' ',1).str[0]
               , price = lambda x: x.price / 1000000
              )
       .replace({'balcony':{np.nan: 0}})
       .astype({'balcony':'category'
                , 'yr_built':'int'
                , 'building_height':'int'
                , 'area':'float'
                , 'flr_lvl':'int'
                , 'window_n':'int'
                , 'window_type':'category'
                , 'door_type':'category'
                , 'mortgage':'category'
                , 'district':'category'
               })
      )

df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6952 entries, 0 to 6951
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   flr_type         6952 non-null   object
 1   balcony          6952 non-null   category
 2   yr_built         6952 non-null   int64
 3   garage           6952 non-null   int64
 4   window_type      6952 non-null   category
 5   building_height  6952 non-null   int64
 6   door_type        6952 non-null   category
 7   area             6952 non-null   float64
 8   flr_lvl          6952 non-null   int64
 9   mortgage         6952 non-null   category
 10  district         6952 non-null   category
 11  window_n         6952 non-null   int64
 12  location         6952 non-null   object
 13  posting_name     6952 non-null   object
 14  posting_link     6952 non-null   object
 15  price            6952 non-null   float64
 16  date_posted      6952 non-null   object
 17  description      6952 non-null   object
dtypes: category(5), float64(2), int64(5), object(6)
memory usage: 741.1+ KB

In [12]:
# !!! code needs improving
def clean_area_col(area,name,desc):
    
    if ((np.ceil(area) == np.ceil(name) == np.ceil(desc)) | (np.floor(area) == np.floor(name) == np.floor(desc))):
        return max(area, name, desc)
    
    elif (name == 99999) & (desc == 99999):
        return area
    
    elif name == 99999:
        if (np.ceil(area) == np.ceil(desc)) | (np.floor(area) == np.floor(desc)):
            return max(area, desc)
        elif desc > 500:
            return area
        elif area > 500:
            return desc
        else:
            return max(area,desc)
        
    elif desc == 99999:
        if (np.ceil(area) == np.ceil(name)) | (np.floor(area) == np.floor(name)):
            return max(area, name)
        elif name > 500:
            return area
        elif area > 500:
            return name
        else:
            return max(area,name)
    
    elif area > 500:
        return max(name,desc)
    
    elif name > 500:
        return max(area, desc)
    
    elif desc > 500:
        return max(area,name)
    
    else:
        return max(area, name, desc)

In [13]:
# extract potential missing values from posting title and description
df4 = (df3
       .assign(area_name = lambda x: x.posting_name.str.extract(r'(\d+,?\.?\d+\s?)[–ºm][¬≤2k–∫]'))
       .assign(area_name = lambda x: x.area_name.str.replace(',', '.'))
       .assign(area_name = lambda x: x.area_name.fillna(99999))
       .assign(area_desc = lambda x: x.description.str.extract(r'(\d+,?\.?\d+\s?)[–ºm][¬≤2k–∫]'))
       .assign(area_desc = lambda x: x.area_desc.str.replace(',', '.'))
       .assign(area_desc = lambda x: x.area_desc.fillna(99999))
       .astype({'area_name':'float',
               'area_desc':'float'})
      )

df4['area_m2'] = df4.apply(lambda x: clean_area_col(x['area'], x['area_name'], x['area_desc']), axis=1)

df4

,flr_type,balcony,yr_built,garage,window_type,building_height,door_type,area,flr_lvl,mortgage,...,window_n,location,posting_name,posting_link,price,date_posted,description,area_name,area_desc,area_m2
0,parquet,2,2021,0,alum,17,burged,79.20,15,bank,...,4,–Ø–∞—Ä–º–∞–≥,–ù–æ–º–∏–Ω –∫–æ–Ω—Å—Ç—Ä–∞–∫—à–Ω—ã —è–∞—Ä–º–∞–≥—Ç garden city 2 —Ç”©—Å”©–ª–¥...,https://www.unegui.mn/adv/5307817_nomin-konstr...,360.0,"”®–Ω”©”©–¥”©—Ä 11:16, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä",‚Äú–ù–û–ú–ò–ù –ö–û–ù–°–¢–†–ê–ö–®–ù‚Äù-—ã –ë“Æ–¢–≠–≠–ù –ë–ê–ô–ì–£–£–õ–ê–õ–¢ GARDENC...,79.20,99999.00,79.20
1,parquet,1,2019,0,vinyl,16,burged,59.00,2,no,...,2,1-—Ä —Ö–æ—Ä–æ–æ–ª–æ–ª,"Harhorin horoolold 58,2mkv 2oroo bair",https://www.unegui.mn/adv/5844945_harhorin-hor...,155.0,"”®–Ω”©”©–¥”©—Ä 11:16, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä","Harhorin horoolold 58,19mkv 2oroo bair hudalda...",58.20,58.19,59.00
2,parquet,1,2018,0,vinyl,12,burged,37.08,11,no,...,2,11-—Ä —Ö–æ—Ä–æ–æ–ª–æ–ª,–•–∞–Ω–≥–∞–π —Ö–æ—Ç—Ö–æ–Ω–¥ 2”©—Ä”©”© –±–∞–π—Ä 37.08–º2,https://www.unegui.mn/adv/5843673_khangai-khot...,98.0,"”®–Ω”©”©–¥”©—Ä 11:16, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä",–•–∞–Ω–≥–∞–π —Ö–æ—Ç—Ö–æ–Ω–¥ 2”©—Ä”©”© 37.08–º–∫–≤ -12/11–¥–∞–≤—Ö–∞—Ä—Ç-–ì—ç...,37.08,37.08,37.08
3,parquet,1,1980,0,vinyl,5,burged,69.00,3,no,...,4,–¢”©–º”©—Ä –∑–∞–º,–¢”©–º”©—Ä –∑–∞–º–¥ 3 ”©—Ä”©”©,https://www.unegui.mn/adv/5632308_tomor-zamd-3...,150.0,"”®–Ω”©”©–¥”©—Ä 11:12, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä","üè°–ë–∞—è–Ω–≥–æ–ª –¥“Ø“Ø—Ä—ç–≥, –¢”©–º”©—Ä –∑–∞–º, –ë–æ–≥–¥ –∞—Ä —Ö–æ—Ä–æ–æ–ª–æ–ª—ã–Ω...",99999.00,69.00,69.00
4,parquet,1,2021,0,vinyl,12,burged,90.39,4,personal,...,4,–ó–∞–π—Å–∞–Ω,–ê–ª—Ç–∞–Ω –±–æ–≥–¥ —Ü–æ–≥—Ü–æ–ª–±–æ—Ä—Ç 4 ”©—Ä”©”© –±–∞–π—Ä,https://www.unegui.mn/adv/5494189_altan-bogd-t...,3.1,"”®–Ω”©”©–¥”©—Ä 11:12, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä",–ó–∞–π—Å–∞–Ω–¥ –±–∞–π—Ä–ª–∞–ª—Ç–∞–π –æ–¥–æ–æ –∞—à–∏–≥–ª–∞–ª—Ç–∞–Ω–¥ –æ—Ä–∂ –±–∞–π–≥–∞–∞...,99999.00,99999.00,90.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6947,parquet,1,2022,0,vinyl,16,burged,52.00,11,no,...,2,–î”©–ª–≥”©”©–Ω –Ω—É—É—Ä,–î”©–ª–≥”©”©–Ω –Ω—É—É—Ä—Ç 2 ”©—Ä”©”© –æ—Ä–æ–Ω —Å—É—É—Ü 52–º2,https://www.unegui.mn/adv/5666728_dolgoon-nuur...,163.0,"2022-02-22 11:54, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä",üíé–û–Ω—Ü–ª–æ–≥ –¥–∞–≤—É—É —Ç–∞–ª üíé‚úÖ –ê –∑—ç—Ä—ç–≥–ª—ç–ª–∏–π–Ω –±“Ø—Å–¥ —á–∞–Ω–∞—Ä—Ç...,52.00,99999.00,52.00
6948,parquet,1,2022,0,vinyl,16,burged,52.06,14,no,...,2,–ë–∞—è–Ω–º–æ–Ω–≥–æ–ª —Ö–æ—Ä–æ–æ–ª–æ–ª,–°–∞—Ä—É—É–ª —Ö–æ—Ä–æ–æ–ª–æ–ª–¥ 2 ”©—Ä”©”© 52.06 –º–∫–≤ –±–∞–π—Ä,https://www.unegui.mn/adv/5781181_saruul-khoro...,3.3,"2022-02-22 11:45, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä",–•–æ—Ç—ã–Ω –ê –∑—ç—Ä—ç–≥–ª—ç–ª–∏–π–Ω –±“Ø—Å—ç–¥ –ë–ó–î 26 —Ä —Ö–æ—Ä–æ–æ–Ω–¥ –°–∞—Ä...,52.06,52.06,52.06
6949,parquet,1,2022,0,vinyl,16,metal,48.50,4,no,...,2,–ë—É—Å–∞–¥,Selbe apartment 2 uruu bair,https://www.unegui.mn/adv/5781105_selbe-apartm...,3.1,"2022-02-22 11:29, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä",Selbe apartment-–¥ 2 ”©—Ä”©”© –±–∞–π—Ä –∑–∞—Ä–Ω–∞. *1–º2 –Ω—å...,99999.00,48.50,48.50
6950,parquet,1,2020,0,vinyl,12,burged,46.15,5,no,...,2,–ë—É—Å–∞–¥,–î—ç–ª–≥—ç—Ä—ç—Ö —Ö–æ—Ç—Ö–æ–Ω–¥ 2 ”©—Ä”©”© –±–∞–π—Ä 46.15–º2,https://www.unegui.mn/adv/5513787_delgerekh-kh...,115.0,"2022-02-22 11:27, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä",–î—ç–ª–≥—ç—Ä—ç—Ö —Ö–æ—Ç—Ö–æ–Ω 80/6 –±–∞–π—Ä–∞–Ω–¥ 2 ”©—Ä”©”© –±–∞–π—Ä –∑–∞—Ä–Ω–∞...,46.15,99999.00,46.15
6951,parquet,1,2011,0,vinyl,15,burged,59.00,14,bank,...,2,UB Town,–•—É–¥-–Ω ub town-–Ω—ã —Ö–æ–π–Ω–æ 2 ”©—Ä”©”© –±–∞–π—Ä .,https://www.unegui.mn/adv/5781049_khud-n-ub-to...,147.0,"2022-02-22 11:22, –£–ª–∞–∞–Ω–±–∞–∞—Ç–∞—Ä",–•–£–î-–∏–π–Ω UB town —Ö–æ—Ç—Ö–æ–Ω—ã –∞—Ä–¥ 59 –º–∫–≤ —Å–∞—Ä—É—É–ª—Ö–∞–Ω —Ç...,99999.00,59.00,59.00

In [14]:
#df4.sort_values('area_m2').iloc[:,np.r_[7, 18:21]].tail(60)

# Manually replace value
df4.at[5078, 'area_m2'] = df4.at[5078, 'area']

In [15]:
# if price less than 20 then usually indicates price per m2
def adjust_price(price, area):
    if price < 20:
        return price * area
    else:
        return(price)

In [16]:
# Prepare for analysis
df5 = (df4
       .drop(columns=['area', 'posting_name', 'date_posted', 'description', 'area_name', 'area_desc', 'posting_link'])
       .query('area_m2 >= 15 & area_m2 < 500')
       .query('price > 0.1')
       .reset_index(drop=True)
      )

df5['price'] = df5.apply(lambda x: adjust_price(x['price'], x['area_m2']), axis=1)

df5.head()

,flr_type,balcony,yr_built,garage,window_type,building_height,door_type,flr_lvl,mortgage,district,window_n,location,price,area_m2
0,parquet,2,2021,0,alum,17,burged,15,bank,KU,4,–Ø–∞—Ä–º–∞–≥,360.000,79.20
1,parquet,1,2019,0,vinyl,16,burged,2,no,SH,2,1-—Ä —Ö–æ—Ä–æ–æ–ª–æ–ª,155.000,59.00
2,parquet,1,2018,0,vinyl,12,burged,11,no,SU,2,11-—Ä —Ö–æ—Ä–æ–æ–ª–æ–ª,98.000,37.08
3,parquet,1,1980,0,vinyl,5,burged,3,no,BG,4,–¢”©–º”©—Ä –∑–∞–º,150.000,69.00
4,parquet,1,2021,0,vinyl,12,burged,4,personal,KU,4,–ó–∞–π—Å–∞–Ω,280.209,90.39

In [17]:
# replace values into correct column
idx = df5.query('flr_lvl > building_height').index.values
idx
df5.iloc[idx, 5], df5.iloc[idx, 7] = df5.iloc[idx, 7], df5.iloc[idx, 5]

In [18]:
df5.to_csv('unegui_clean.csv', index=False)